### ISSUE TITLE
Asking a few questions

### ISSUE THREAD

**Issue by The1mann0** [masterplane8/F1-League-Management#5] opened 2021-10-19 21:57 UTC
Hi,

In which pages should I manually enter information and which should automatically fill out?

A potential issue I found was when entering 'Grid Position' under 'Race Reports' ,over in 'Driver statistics' it gave every driver a 'Pole Position', is this an issue at my end?
<img width="343" alt="IMG1" src="https://user-images.githubusercontent.com/92828014/137996078-059072bc-56bf-49de-b1cc-bdb340770224.PNG">
Additionally, it doesn't register anyone to be racing.
<img width="548" alt="IMG2" src="https://user-images.githubusercontent.com/92828014/137996151-8c312486-f42b-48f1-9c59-d40d74bd36b3.PNG">

Again could be at my end, but should the 'Race Results and Qualifying Results pages be automatically updating? (I manually entered the driver names, did I go wrong here?)
<img width="786" alt="img3" src="https://user-images.githubusercontent.com/92828014/137996330-bdb0d737-c67a-4bb1-adf9-4e61199105b4.PNG">

**Comment by masterplane8** [comment] 2021-10-19 22:25
Hey @The1mann0,

A couple of things are currently being fixed and will work as intended in the update coming out tonight. In principle, the only areas that you need to fill out are the following fields:

### League Management

Firstly, there are instruction for each section at the top of the tabs. Read those for assistance as you fill in information. 
 - **Track List**: Select the tracks from the drop down menu in each cell.
 - **Drivers**: Enter the name of all of your drivers here. The sheet will populate the cells in other pages where names are referenced. Keep in mind, you can not remove names once the season begins. There is more information and instruction at the top of the tab. 
 - **Team Assignments**: In each cell for each position of each team, a drop down menu will list all of the drivers you entered into the **Drivers** tab. Assign your drivers to teams here. 
 - **Mid-Season Driver Transfers**: Please read the instructions on the tab. You will not have to use this right off the bat. 
 - **League Settings**: Look through this tab and make sure everything is set to how you want it. If you are changing points per position, make sure to change the preset to "None" and activate points for bottom 10 finishers if you wish.

### Results Tables

The only fields you should be entering information to are the columns of each race with the heading of:
- Grid Start
- Time From Leader
- Fastest Lap
- Reserve Team (if applicable)
- Penalties (located to the right of each main table)
- Manual Champ. Pts. (if you need to adjust points for each race).

### Every other cell on this sheet updates automatically based on the cells listed above.

Lastly, notice the note I left on the Race Results and Qualifying Results pages. There are many columns that are greyed out in the photo you sent, and that is because they are not in use. If you wish, you can hide these columns. If you need help doing that, [here](https://support.microsoft.com/en-us/office/hide-or-show-rows-or-columns-659c2cad-802e-44ee-a614-dde8443579f8) is link for instructions. If you have any more questions or you need things to be described in more detail, I'd be happy to help.

**Comment by The1mann0** [comment] 2021-10-20 02:27
this is just a tester, but am I entering something wrong?
<img width="277" alt="img4" src="https://user-images.githubusercontent.com/92828014/138017849-aed5d25f-6ecd-441d-99c7-fd3ceb8953a8.PNG">

**Comment by masterplane8** [comment] 2021-10-20 02:44
After a clean install of the excel sheet, I enter in the names of my drivers to **Drivers** and assign them to teams in **Team Assignments.** Below is what that looks like:

![Screen Shot 2021-10-19 at 10 36 49 PM](https://user-images.githubusercontent.com/50423545/138018963-c48fe39e-bf59-4ff8-8478-07830cd4dbda.png)

When I navigate to the Results Tables, the names have already transferred over. After the first face is done, I enter in all of the information given and it looks something like this:

![Screen Shot 2021-10-19 at 10 37 57 PM](https://user-images.githubusercontent.com/50423545/138019264-d51f88f1-067e-4c69-be9c-fc1f9e81b7f3.png)

If you follow these steps directly, after a clean install, and the problem persists, I may ask you to share your sheet with me so I can analyze the problem further.

**Comment by The1mann0** [comment] 2021-10-20 02:56
Apologies, can we organise a zoom meet to sort it out.
I put in the same data and the results column is still not filling in, nor any other information on other pages.

Cheers

**Comment by masterplane8** [comment] 2021-10-20 03:12
If you have not purchased Excel, you can still use the webpage version for free. Just search OneDrive.com, upload F1LM v1.31 there, and the webpage version of Excel will open up.

**Comment by masterplane8** [comment] 2021-10-20 03:14
Do me a favor and try the webpage version  of Excel to see if it works there. This is a known problem that I am working to fix.

**Closed** 2021-10-20 03:35 UTC
